services:
  db1:
    image: 'postgres:latest'
    environment:
      POSTGRES_DB: curso_springboot
      POSTGRES_PASSWORD: a1b2c3d4
      POSTGRES_USER: devdb
    volumes:
      - ./data/db1:/var/lib/postgresql/data
    ports:
      - '54321:5432'
    networks:
      - red-backend-app

  db2:
    image: 'postgres:latest'
    environment:
      POSTGRES_DB: curso_springboot
      POSTGRES_USER: devdb
      POSTGRES_PASSWORD: a1b2c3d4
    volumes:
      - ./data/db2:/var/lib/postgresql/data
    ports:
      - "54322:5432"
    networks:
      - red-backend-app

  pais-service:
    image: 'alvarosalazar/pais-service:latest'
    ports:
      - '8082:8080'
    depends_on:
      - db1
    environment:
      DB_URL: jdbc:postgresql://db1/curso_springboot
      DB_USERNAME: devdb
      DB_PASSWORD: a1b2c3d4
      JPA_DDL: create-drop
    networks:
      - red-backend-app

  auth-service:
    image: 'alvarosalazar/auth-service:latest'
    ports:
      - '8081:8080'
    depends_on:
      - db2
    environment:
      DB_URL: jdbc:postgresql://db2/curso_springboot
      DB_USERNAME: devdb
      DB_PASSWORD: a1b2c3d4
      JPA_DDL: create-drop
    networks:
      - red-backend-app
networks:
  red-backend-app:
    driver: bridge