services:
  mosquitto:
    image: eclipse-mosquitto:latest
    container_name: mosquitto
    restart: unless-stopped
    ports:
      - "1883:1883"
      - "9001:9001"
    volumes:
      - ./mosquitto/conf:/mosquitto/conf
      - ./mosquitto/data:/mosquitto/data
      - ./mosquitto/logs:/mosquitto/logs